import './globals.css'
import Nav from "./auth/Nav";
import { Roboto } from 'next/font/google'
import Toast from './components/Toast';

export const metadata = {
  title: 'Socailise',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: "--font-roboto"
})

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${roboto.variable} mx-4 md:mx-48 xl:mx-96`}>
        <Nav />
        <Toast />
        {children}
      </body>
    </html>
  )
}
