import './globals.css'
import Nav from "./auth/Nav";
import { Roboto } from 'next/font/google'
import QueryWrapper from './helper/QueryWrapper';

export const metadata = {
  title: 'Socailise',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: "--font-roboto"
})

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} mx-4 md:mx-48 xl:mx-96`}>
        <QueryWrapper>
          <Nav />
          {children}
        </QueryWrapper>
      </body>
    </html>
  )
}
